// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DBWriterService.proto

package com.citi.olympus.grpc.stub;

public final class DBWriterService {
  private DBWriterService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TradeDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reqTime = 1;</code>
     * @return The reqTime.
     */
    java.lang.String getReqTime();
    /**
     * <code>string reqTime = 1;</code>
     * @return The bytes for reqTime.
     */
    com.google.protobuf.ByteString
        getReqTimeBytes();
  }
  /**
   * Protobuf type {@code TradeDataRequest}
   */
  public  static final class TradeDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TradeDataRequest)
      TradeDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TradeDataRequest.newBuilder() to construct.
    private TradeDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TradeDataRequest() {
      reqTime_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TradeDataRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TradeDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqTime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.class, com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.Builder.class);
    }

    public static final int REQTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqTime_;
    /**
     * <code>string reqTime = 1;</code>
     * @return The reqTime.
     */
    public java.lang.String getReqTime() {
      java.lang.Object ref = reqTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqTime_ = s;
        return s;
      }
    }
    /**
     * <code>string reqTime = 1;</code>
     * @return The bytes for reqTime.
     */
    public com.google.protobuf.ByteString
        getReqTimeBytes() {
      java.lang.Object ref = reqTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest)) {
        return super.equals(obj);
      }
      com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest other = (com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest) obj;

      if (!getReqTime()
          .equals(other.getReqTime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQTIME_FIELD_NUMBER;
      hash = (53 * hash) + getReqTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TradeDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TradeDataRequest)
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.class, com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.Builder.class);
      }

      // Construct using com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reqTime_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataRequest_descriptor;
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest getDefaultInstanceForType() {
        return com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest build() {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest buildPartial() {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest result = new com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest(this);
        result.reqTime_ = reqTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest) {
          return mergeFrom((com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest other) {
        if (other == com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest.getDefaultInstance()) return this;
        if (!other.getReqTime().isEmpty()) {
          reqTime_ = other.reqTime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object reqTime_ = "";
      /**
       * <code>string reqTime = 1;</code>
       * @return The reqTime.
       */
      public java.lang.String getReqTime() {
        java.lang.Object ref = reqTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqTime = 1;</code>
       * @return The bytes for reqTime.
       */
      public com.google.protobuf.ByteString
          getReqTimeBytes() {
        java.lang.Object ref = reqTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqTime = 1;</code>
       * @param value The reqTime to set.
       * @return This builder for chaining.
       */
      public Builder setReqTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqTime() {
        
        reqTime_ = getDefaultInstance().getReqTime();
        onChanged();
        return this;
      }
      /**
       * <code>string reqTime = 1;</code>
       * @param value The bytes for reqTime to set.
       * @return This builder for chaining.
       */
      public Builder setReqTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqTime_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TradeDataRequest)
    }

    // @@protoc_insertion_point(class_scope:TradeDataRequest)
    private static final com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest();
    }

    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradeDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<TradeDataRequest>() {
      @java.lang.Override
      public TradeDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TradeDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TradeDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradeDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.citi.olympus.grpc.stub.DBWriterService.TradeDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TradeDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TradeDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string respTime = 1;</code>
     * @return The respTime.
     */
    java.lang.String getRespTime();
    /**
     * <code>string respTime = 1;</code>
     * @return The bytes for respTime.
     */
    com.google.protobuf.ByteString
        getRespTimeBytes();

    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();
  }
  /**
   * Protobuf type {@code TradeDataResponse}
   */
  public  static final class TradeDataResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TradeDataResponse)
      TradeDataResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TradeDataResponse.newBuilder() to construct.
    private TradeDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TradeDataResponse() {
      respTime_ = "";
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TradeDataResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TradeDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              respTime_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.class, com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.Builder.class);
    }

    public static final int RESPTIME_FIELD_NUMBER = 1;
    private volatile java.lang.Object respTime_;
    /**
     * <code>string respTime = 1;</code>
     * @return The respTime.
     */
    public java.lang.String getRespTime() {
      java.lang.Object ref = respTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        respTime_ = s;
        return s;
      }
    }
    /**
     * <code>string respTime = 1;</code>
     * @return The bytes for respTime.
     */
    public com.google.protobuf.ByteString
        getRespTimeBytes() {
      java.lang.Object ref = respTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        respTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 2;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRespTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, respTime_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRespTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, respTime_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse)) {
        return super.equals(obj);
      }
      com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse other = (com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse) obj;

      if (!getRespTime()
          .equals(other.getRespTime())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPTIME_FIELD_NUMBER;
      hash = (53 * hash) + getRespTime().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TradeDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TradeDataResponse)
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.class, com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.Builder.class);
      }

      // Construct using com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        respTime_ = "";

        key_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.citi.olympus.grpc.stub.DBWriterService.internal_static_TradeDataResponse_descriptor;
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse getDefaultInstanceForType() {
        return com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse build() {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse buildPartial() {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse result = new com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse(this);
        result.respTime_ = respTime_;
        result.key_ = key_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse) {
          return mergeFrom((com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse other) {
        if (other == com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse.getDefaultInstance()) return this;
        if (!other.getRespTime().isEmpty()) {
          respTime_ = other.respTime_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object respTime_ = "";
      /**
       * <code>string respTime = 1;</code>
       * @return The respTime.
       */
      public java.lang.String getRespTime() {
        java.lang.Object ref = respTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          respTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string respTime = 1;</code>
       * @return The bytes for respTime.
       */
      public com.google.protobuf.ByteString
          getRespTimeBytes() {
        java.lang.Object ref = respTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          respTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string respTime = 1;</code>
       * @param value The respTime to set.
       * @return This builder for chaining.
       */
      public Builder setRespTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        respTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string respTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRespTime() {
        
        respTime_ = getDefaultInstance().getRespTime();
        onChanged();
        return this;
      }
      /**
       * <code>string respTime = 1;</code>
       * @param value The bytes for respTime to set.
       * @return This builder for chaining.
       */
      public Builder setRespTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        respTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 2;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 2;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TradeDataResponse)
    }

    // @@protoc_insertion_point(class_scope:TradeDataResponse)
    private static final com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse();
    }

    public static com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TradeDataResponse>
        PARSER = new com.google.protobuf.AbstractParser<TradeDataResponse>() {
      @java.lang.Override
      public TradeDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TradeDataResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TradeDataResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TradeDataResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.citi.olympus.grpc.stub.DBWriterService.TradeDataResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeDataResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025DBWriterService.proto\"#\n\020TradeDataRequ" +
      "est\022\017\n\007reqTime\030\001 \001(\t\"2\n\021TradeDataRespons" +
      "e\022\020\n\010respTime\030\001 \001(\t\022\013\n\003key\030\002 \001(\t2N\n\014Writ" +
      "eService\022>\n\021validateTradeData\022\021.TradeDat" +
      "aRequest\032\022.TradeDataResponse\"\000(\001B\034\n\032com." +
      "citi.olympus.grpc.stubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TradeDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TradeDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeDataRequest_descriptor,
        new java.lang.String[] { "ReqTime", });
    internal_static_TradeDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TradeDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeDataResponse_descriptor,
        new java.lang.String[] { "RespTime", "Key", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
